---
title: "5241 zhengli"
output: html_document
---

```{r}
getwd()
setwd("C:/Users/ricoc/Desktop/Columbia University Study/Stat 5241 Statistical Machine Learning/GR5241_FinalProject-main/Data")
communities <- read.csv("communities_kmeans.csv", header=T)
communities
```


```{r}
communities$KmeansLabel <- factor(communities$KmeansLabel,levels = c("0","1"))
communities
library(dplyr)
comwithrace =
  communities%>%
  select(-(state:fold)) %>%
  print()
head(comwithrace)
```

```{r}
set.seed(2021)
library(rsample)
data_split <- initial_split(comwithrace, prop = .8)
train <- training(data_split)
test  <- testing(data_split)
```

```{r}
library(glmnet)
Xfull <- model.matrix(ViolentCrimesPerPop ~ ., data = train)
Xfull <- Xfull[, -1] # the Lasso will add its own intercept to the model</pre>
Y <- train$ViolentCrimesPerPop
lambdas <- 10^{seq(from = -7, to = 2, length = 100)}
lafit <- glmnet(Xfull, Y, alpha = 1, lambda = lambdas)
plot(lafit, xvar = "lambda",label = F)
cv.rrfit <- cv.glmnet(Xfull, Y, alpha = 1, lambda = lambdas) 
plot(cv.rrfit)
lammin <- cv.rrfit$lambda.min
lam1se <- cv.rrfit$lambda.1se
rr.best <- glmnet(Xfull, Y, alpha = 1, lambda = lammin)
rr.se <- glmnet(Xfull, Y, alpha = 1, lambda = lam1se)
coef(rr.best)

```
```{r}
library(DAAG)
Lasso.lm <- lm(ViolentCrimesPerPop ~.-racePctHisp-agePct12t21-agePct16t24-medIncome-medFamInc-perCapInc-NumUnderPov-PctNotHSGrad-PctBSorMore-PctOccupManu-PctOccupMgmtProf-FemalePctDiv-TotalPctDiv-PersPerFam-PctFam2Par-PctTeen2Par-PctWorkMomYoungKids-NumIlleg-PctImmigRecent-PctImmigRec10-PctRecentImmig-PctRecImmig5-PctSpeakEnglOnly-PctNotSpeakEnglWell-PctLargHouseFam-PctLargHouseOccup-PersPerOccupHous-PersPerOwnOccHous-PersPerRentOccHous-MedNumBR-PctHousOwnOcc-MedYrHousBuilt-PctHousNoPhone-PctWOFullPlumb-OwnOccLowQuart-OwnOccMedVal-OwnOccHiQuart-RentMedian-RentHighQ-MedOwnCostPctInc-PctForeignBorn-PctBornSameState-PctSameHouse85-PctSameState85-LandArea-PopDens, data = train)
vifless5<-vif(Lasso.lm)
names(vifless5) <- names(vif(Lasso.lm))
vifless5 <- vifless5[vifless5 < 5]
vifless5
```



```{r}
Lasso.lm1 <- lm(ViolentCrimesPerPop ~ racePctAsian+ pctUrban+pctWFarmSelf+pctWRetire+blackPerCap+indianPerCap+AsianPerCap+HispPerCap+PctEmplManu+PctEmplProfServ+PctWorkMom+ NumImmig+PctHousOccup+PctVacantBoarded+PctVacMore6Mos+ MedRentPctHousInc+MedOwnCostPctInc+NumInShelters+NumStreet+PctSameCity85+PctUsePubTrans+ LemasPctOfficDrugUn + KmeansLabel, data = train)
summary(Lasso.lm1)
plot(Lasso.lm1)

```
```{r}
library(dplyr)
forla =
  train%>%
  select(ViolentCrimesPerPop , racePctAsian ,pctUrban , 
    pctWFarmSelf , pctWRetire , blackPerCap , indianPerCap , 
    AsianPerCap , HispPerCap , PctEmplManu , PctEmplProfServ , 
    PctWorkMom , NumImmig , PctHousOccup , PctVacantBoarded , 
    PctVacMore6Mos , MedRentPctHousInc , MedOwnCostPctInc , NumInShelters , 
    NumStreet , PctSameCity85 , PctUsePubTrans , LemasPctOfficDrugUn,KmeansLabel) %>%
  print()
head(forla)
library(Hmisc)
hist.data.frame(forla)
```

```{r}
Lasso.lm1t <- lm(sqrt(ViolentCrimesPerPop) ~ sqrt(racePctAsian)+ (sqrt(max(pctUrban+1) - pctUrban))+sqrt(pctWFarmSelf)+pctWRetire+sqrt(blackPerCap)+sqrt(indianPerCap)+sqrt(AsianPerCap)+sqrt(HispPerCap)+PctEmplManu+PctEmplProfServ+PctWorkMom+ sqrt(NumImmig)+(sqrt(max(PctHousOccup+1) - PctHousOccup))+sqrt(PctVacantBoarded)+PctVacMore6Mos+ MedRentPctHousInc+MedOwnCostPctInc+sqrt(NumInShelters)+sqrt(NumStreet)+(sqrt(max(PctSameCity85+1) - PctSameCity85))+sqrt(PctUsePubTrans)+ sqrt(LemasPctOfficDrugUn)+KmeansLabel, data = forla)
summary(Lasso.lm1t)
plot(Lasso.lm1t)

```




```{r}
coef(rr.se)
```


```{r}
library(DAAG)
Lasso.1se <- lm(ViolentCrimesPerPop ~racepctblack+racePctWhite+agePct12t29+pctUrban+MalePctDivorce+PctKids2Par+PctWorkMom+PctIlleg+PctPersDenseHous+HousVacant+PctHousOccup+PctVacantBoarded+NumStreet+KmeansLabel, data = train)
vifless55<-vif(Lasso.1se)
names(vifless55) <- names(vif(Lasso.1se))
vifless55 <- vifless55[vifless55 < 5]
vifless55
```


```{r}
Lasso.1se1 <- lm(ViolentCrimesPerPop ~ agePct12t29+pctUrban+MalePctDivorce+PctWorkMom+PctPersDenseHous+HousVacant+PctHousOccup+PctVacantBoarded+NumStreet+KmeansLabel, data = train)
summary(Lasso.1se1)
plot(Lasso.1se1)

```





```{r}
library(dplyr)
forla1 =
  train%>%
  select( agePct12t29,pctUrban,MalePctDivorce,PctWorkMom,PctPersDenseHous,HousVacant,PctHousOccup,PctVacantBoarded,NumStreet,ViolentCrimesPerPop,KmeansLabel ) %>%
  print()
head(forla1)
library(Hmisc)
hist.data.frame(forla1)
```

```{r}
Lasso.1se1t <- lm(sqrt(ViolentCrimesPerPop) ~ agePct12t29+(sqrt(max(pctUrban+1) - pctUrban))+MalePctDivorce+PctWorkMom+sqrt(PctPersDenseHous)+sqrt(HousVacant)+(sqrt(max(PctHousOccup+1) - PctHousOccup))+sqrt(PctVacantBoarded)+sqrt(NumStreet)+KmeansLabel, data = forla1)
summary(Lasso.1se1t)
plot(Lasso.1se1t)
```
```{r}
forla1$KmeansLabel <- factor(forla1$KmeansLabel,levels = c("0","1"))
kmeans0 <- forla1[forla1$KmeansLabel=="0",]
kmeans1<- forla1[forla1$KmeansLabel=="1",]
Lasso.1se1t0 <- lm(sqrt(ViolentCrimesPerPop) ~ agePct12t29+(sqrt(max(pctUrban+1) - pctUrban))+MalePctDivorce+PctWorkMom+sqrt(PctPersDenseHous)+sqrt(HousVacant)+(sqrt(max(PctHousOccup+1) - PctHousOccup))+sqrt(PctVacantBoarded)+sqrt(NumStreet), data = kmeans0)
Lasso.1se1t1 <- lm(sqrt(ViolentCrimesPerPop) ~ agePct12t29+(sqrt(max(pctUrban+1) - pctUrban))+MalePctDivorce+PctWorkMom+sqrt(PctPersDenseHous)+sqrt(HousVacant)+(sqrt(max(PctHousOccup+1) - PctHousOccup))+sqrt(PctVacantBoarded)+sqrt(NumStreet), data = kmeans1)

```
```{r}

```

```{r}

mean((Lasso.1se1t$residuals)^2)
mean((Lasso.lm1t$residuals)^2)
```

```{r}
prediction0<- predict(Lasso.1se1t0, test)
prediction1<- predict(Lasso.1se1t1, test)
```

```{r}
output <- cbind(test, prediction)

```

```{r}
plot(prediction,test$ViolentCrimesPerPop)
abline(coef = c(0,1))

```

```{r}
pd<- predict(Lasso.1se1t0, kmeans0)
op <- cbind(kmeans0, pd)
```

```{r}
write.csv(op,"C:/Users/ricoc/desktop\\opt111.csv", row.names = T)
```

```{r}
mean((pd-kmeans0$ViolentCrimesPerPop)^2)
mean((prediction-test$ViolentCrimesPerPop)^2)
```


```{r}
X1123<- model.matrix(sqrt(ViolentCrimesPerPop)~agePct12t29+sqrt(max(pctUrban+1) - pctUrban)+MalePctDivorce+PctWorkMom+sqrt(PctPersDenseHous)+sqrt(HousVacant)+sqrt(max(PctHousOccup+1) - PctHousOccup)+sqrt(PctVacantBoarded)+sqrt(NumStreet),data = forla1)
X1123 <- X1123[,-1]
y1<- sqrt(forla1$ViolentCrimesPerPop)
cv <- cv.glmnet(x = X1123, 
            y = y1)
cv$cvm[cv$lambda == cv$lambda.1se] 
```

```{r}
set.seed(2021)
library(rsample)
data_split <- initial_split(communities, prop = .8)
train <- training(data_split)
test  <- testing(data_split)
train$KmeansLabel <- factor(train$KmeansLabel,levels = c("0","1"))
kmeans0 <- train[train$KmeansLabel=="0",]
kmeans1<- train[train$KmeansLabel=="1",]
ttest0<- test[test$KmeansLabel=="0",]
ttest1<- test[test$KmeansLabel=="1",]
Lasso.1se1t0 <- lm(sqrt(ViolentCrimesPerPop) ~ agePct12t29+(sqrt(max(pctUrban+1) - pctUrban))+MalePctDivorce+PctWorkMom+sqrt(PctPersDenseHous)+sqrt(HousVacant)+(sqrt(max(PctHousOccup+1) - PctHousOccup))+sqrt(PctVacantBoarded)+sqrt(NumStreet), data = kmeans0)
Lasso.1se1t1 <- lm(sqrt(ViolentCrimesPerPop) ~ agePct12t29+(sqrt(max(pctUrban+1) - pctUrban))+MalePctDivorce+PctWorkMom+sqrt(PctPersDenseHous)+sqrt(HousVacant)+(sqrt(max(PctHousOccup+1) - PctHousOccup))+sqrt(PctVacantBoarded)+sqrt(NumStreet), data = kmeans1)

```

```{r}
pd1<- predict(Lasso.1se1t0, ttest0)
op <- cbind(ttest0, pd1)
write.csv(op,"C:/Users/ricoc/desktop\\k00.csv", row.names = T)
```

```{r}
kout<- read.csv("C:/Users/ricoc/Desktop/k11.csv", header=T)
ktest<- read.csv("C:/Users/ricoc/Desktop/k00.csv", header=T)
```

```{r}
mean((kout$pd1-kout$ViolentCrimesPerPop)^2)
mean((ktest$pd1-ktest$ViolentCrimesPerPop)^2)
```